name: Build and Push Docker image (ARM64 native)

on:
  push:
    branches:
      - main
      - docker-ci
    paths:
      - Dockerfile
      - '**/*.py'
      - .github/workflows/docker-build.yml
  pull_request: {}

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ${{ github.event.repository.name }}
      IMAGE_OWNER: ${{ github.repository_owner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (native ARM64)
        run: |
          IMAGE_REPO="ghcr.io/$(echo $IMAGE_OWNER | tr '[:upper:]' '[:lower:]')/$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')"
          docker build -t $IMAGE_REPO:latest .
          docker push $IMAGE_REPO:latest
